Bug fixes to media gallery
breatheco-de/admin pull request #127
Opened 2021-07-13 03:57 UTC by Omonroy36

2021-07-13 21:21 UTC, ArielCalisaya requested changes

2021-07-13 21:21 UTC, ArielCalisaya commented on src/app/services/breathecode.js
> +                .join("&")
change js quotes elements to `single-quote`

2021-07-13 21:21 UTC, ArielCalisaya commented on src/app/views/admissions/student-form/NewStudent.jsx
> +//atob
remove unused comments

2021-07-13 21:21 UTC, ArielCalisaya commented on src/app/views/admissions/student-form/NewStudent.jsx
> +  const baseData = query.has("data") ? JSON.parse(atob(query.get("data"))) : null;
use `single-quotes` in javascript elements

2021-07-13 21:21 UTC, ArielCalisaya commented on src/app/views/events/events.jsx
> +import { SmartMUIDataTable } from 'app/components/SmartDataTable';
ESlint expects relative import like `../../../components/etc`

2021-07-13 21:21 UTC, ArielCalisaya commented on src/app/views/admissions/students.jsx
> +import { Breadcrumb } from 'matx';
ESlint expects relative import like `../../../components/etc`

2021-07-13 21:21 UTC, ArielCalisaya commented on src/app/views/feedback/answers.jsx
> +import { Breadcrumb } from 'matx';
ESlint expects relative import like `../../../components/etc`

2021-07-13 21:21 UTC, ArielCalisaya commented on src/app/views/leads/leads.jsx
> +import { SmartMUIDataTable } from 'app/components/SmartDataTable';
ESlint expects relative import like `../../../components/etc`

2021-07-20 02:05 UTC, ArielCalisaya approved these changes

2021-07-20 21:44 UTC, alesanchezr approved these changes

2021-07-23 19:45 UTC, ArielCalisaya approved these changes

2021-07-23 22:24 UTC, merged