Development
breatheco-de/admin pull request #14
Opened 2021-02-05 00:26 UTC by alexscoelho

UI/UX For certificates #820

2021-02-05 02:37 UTC, alesanchezr requested changes
Te hice varios comentarios que quisiera revisaras / cambiaras o me dieras tu opinion.

2021-02-05 02:37 UTC, alesanchezr commented on src/app/navigations.js
> +    // {
Porque comentaste esto? No dejes comentarios sucios, de todas formas creo que si deberias tener esta seccion del menu porque `Coursework` es para otra cosa, es para las asignaciones a los alumnos, tu seccion del menu es certificate.

2021-02-05 02:37 UTC, alesanchezr commented on src/app/navigations.js
> +
creo que esto no va, a ti no te toca coursework

2021-02-05 02:37 UTC, alesanchezr commented on src/app/components/AutocompleteCohorts.js
> +export const AutocompleteCohorts = ({buttonLabel, addTo, setState, placeholder, size, width, setCohortSlug, setCertificateForm}) => {
viste como orlando unifico todos los Autocomplete en uno solo? creo que ya no deberias crear un AutocmpleteCohorts sino utilizar el AsyncAutocomplete que los unifica todos en un solo componente, revisa ese componente y como orlando lo esta utilizando.

2021-02-05 02:37 UTC, alesanchezr commented on src/app/views/admissions/cohort-form/NewCohort.js
> +  console.log("cert:", cert)
borra esto

2021-02-05 02:37 UTC, alesanchezr commented on src/app/views/certificates/Certificates.js
> +import React, { useState, useEffect } from "react";
porque el nombre de esta vista es `Certificates` si los demas de las otras carpetas estan en minustula todos? por ejemplo `cohorts.js`, los componentes si pueden estar en PascalCase pero las vistas en minuscula.

2021-02-05 02:37 UTC, alesanchezr commented on src/app/views/certificates/certificates-utils/CohortAutoComplete.js
> +import axios from "../../../../axios";
Todo este comopnent `CohortAutoComplete` no es igual que `AutocompleteCohorts`? cual es la diferencia?

2021-02-05 02:37 UTC, alesanchezr commented on src/app/views/certificates/certificates-utils/StudentAutoComplete.js
> +import axios from "../../../../axios";
Lo mismo me pasa con este comopnent `StudentAutoComplete`, que diferencia tiene con `CohortAutoComplete`? no se puede unificar no se puede reusar con AsyncAutocomplete?

2021-02-05 02:37 UTC, alesanchezr commented on src/app/views/dashboard/Analytics.jsx
> +        const academyId = JSON.parse(localStorage.getItem("academy_id"));
porque hay que tener academy_id y bc-academy? porque no podemos tener solo bc-academy?

2021-02-05 16:16 UTC, alexscoelho commented on src/app/navigations.js
> +    // {
Perfecto, limpie el codigo comentado, deje el coursework separado de certificates. Me di cuenta que certificates estaba duplicado creo que fue cuando arregle conflictos lo duplique.

2021-02-05 16:19 UTC, alexscoelho commented on src/app/navigations.js
> +
perfecto, lo borre de alli

2021-02-07 21:08 UTC, alexscoelho commented on src/app/components/AutocompleteCohorts.js
> +export const AutocompleteCohorts = ({buttonLabel, addTo, setState, placeholder, size, width, setCohortSlug, setCertificateForm}) => {
Listo ya estoy usando AsyncAutocomplete

2021-02-07 21:08 UTC, alexscoelho commented on src/app/views/admissions/cohort-form/NewCohort.js
> +  console.log("cert:", cert)
Listo

2021-02-07 21:11 UTC, alexscoelho commented on src/app/views/certificates/certificates-utils/StudentAutoComplete.js
> +import axios from "../../../../axios";
Perfecto, listo

2021-02-07 21:16 UTC, alexscoelho commented on src/app/views/dashboard/Analytics.jsx
> +        const academyId = JSON.parse(localStorage.getItem("academy_id"));
Esto recuerdo que lihice por que cuando iniciaba con mis credenciales no me guardaba en el localstorage el bc-academy y por eso le hice ese parche alli.

2021-02-07 21:28 UTC, alexscoelho commented on src/app/views/certificates/certificates-utils/CohortAutoComplete.js
> +import axios from "../../../../axios";
Eliminado

2021-02-07 21:43 UTC, alexscoelho commented
update with suggested corrections.

2021-02-08 02:40 UTC, alesanchezr requested changes

2021-02-08 02:40 UTC, alesanchezr commented on src/app/views/certificates/NewCertificate.js
> +// import {AutocompleteUsers} from "../../components/AutocompleteUsers"
remove the comment.. another thing... why are you using AutocompelteCohorts? Re-use the AsyncAutcomplete component instead.

2021-02-09 22:43 UTC, alesanchezr approved these changes

2021-02-09 22:43 UTC, merged