Changes to forms, staff and student views changes
breatheco-de/admin pull request #18
Opened 2021-02-12 23:25 UTC by Omonroy36

2021-02-13 01:25 UTC, alesanchezr requested changes

2021-02-13 01:25 UTC, alesanchezr commented on src/app/components/Autocomplete.js
> +        id="async_autocomplete"
Para que usas este ID?

2021-02-13 01:25 UTC, alesanchezr commented on src/app/views/admissions/staff-form/NewStaff.js
> +      axios.post(`${process.env.REACT_APP_API_HOST}/v1/auth/academy/member`, { ...refactor, role: role.slug })
Hemos hablado ya otras veces de que esta funcion que llama al API de breathecode debe estar en services/breathecode.js.

Todas las llamdas al API de rbreathecode debe estar alli metidas.

2021-02-13 01:25 UTC, alesanchezr commented on src/app/views/admissions/staff-form/NewStaff.js
> +          if (data.status === 201) {
Esto no puede estarse manejando siempre localmente en cada componente, tienes que migrar esto tambien a una funcion centralizada que sea capaz de procesar cualquier respuesta del API de breathecode de forma automatica, no importa que `status code` o el formato del body payload.

2021-02-13 01:25 UTC, alesanchezr commented on src/app/views/admissions/staff-form/StaffDetails.js
> +  }
esto va para services/breathecode.js

2021-02-13 01:25 UTC, alesanchezr commented on src/app/views/admissions/staff-form/StaffDetails.js
> +  }
esto va para services/breathecode.js

2021-02-13 01:25 UTC, alesanchezr commented on src/app/views/admissions/staff-form/index.js
>    }
esto va para services/breathecode.js

2021-02-13 01:25 UTC, alesanchezr commented on src/app/views/admissions/student-form/StudentDetails.js
>              console.log(error)
esto va para services/breathecode.js

2021-02-13 01:25 UTC, alesanchezr commented on src/app/views/admissions/student-form/student-utils/ProfileForm.js
>              .catch(error => {
esto va para services/breathecode.js

2021-02-13 01:25 UTC, alesanchezr commented on src/app/views/events/forms/EventForm.js
> +                .catch(error => {
esto va para services/breathecode.js

2021-02-16 21:18 UTC, merged

2021-02-17 21:22 UTC, Omonroy36 commented on src/app/views/admissions/staff-form/NewStaff.js
> +      axios.post(`${process.env.REACT_APP_API_HOST}/v1/auth/academy/member`, { ...refactor, role: role.slug })
Change done

2021-02-17 21:22 UTC, Omonroy36 commented on src/app/views/admissions/staff-form/StaffDetails.js
> +  }
Change done

2021-02-17 21:23 UTC, Omonroy36 commented on src/app/components/Autocomplete.js
> +        id="async_autocomplete"
It comes with the original component

2021-02-17 21:23 UTC, Omonroy36 commented on src/app/views/admissions/staff-form/index.js
>    }
Done

2021-02-17 21:23 UTC, Omonroy36 commented on src/app/views/admissions/student-form/student-utils/ProfileForm.js
>              .catch(error => {
Done

2021-02-17 21:23 UTC, Omonroy36 commented on src/app/views/events/forms/EventForm.js
> +                .catch(error => {
Done

2021-02-17 21:23 UTC, Omonroy36 commented on src/app/views/admissions/staff-form/StaffDetails.js
> +  }
Done

2021-02-17 21:24 UTC, Omonroy36 commented on src/app/views/admissions/student-form/StudentDetails.js
>              console.log(error)
Done