Syllabus menu
breatheco-de/admin pull request #336
Opened 2023-01-27 01:42 UTC by aayalapalacin

2023-02-01 13:48 UTC, aayalapalacin commented
@tommygonzaleza fixed navigation bug

2023-02-07 19:07 UTC, tommygonzaleza requested changes

2023-02-07 19:07 UTC, tommygonzaleza commented on src/app/views/admin/routes.js
> +        path: "/admissions/syllabus",
Move it to the views/admissions/routes.js

2023-02-08 15:45 UTC, tommygonzaleza approved these changes

2023-03-07 18:46 UTC, tommygonzaleza approved these changes

2023-03-07 18:51 UTC, merged