Updated at review
breatheco-de/admin pull request #352
Opened 2023-04-04 04:20 UTC by etolopez

2023-05-02 02:47 UTC, tommygonzaleza approved these changes

2023-05-05 18:15 UTC, tommygonzaleza requested changes

2023-05-05 18:15 UTC, tommygonzaleza commented on src/app/views/media/components/ComposeAsset.js
> +                onOpen={()=>{ saveAsset(formattedDate); setDirty(false); handleAction('push')}}
Estas agregando el hanldeAction('push') on open y onclose, no deberia ser solo en uno de los dos?

2023-06-27 17:11 UTC, tommygonzaleza approved these changes

2023-06-27 17:19 UTC, tommygonzaleza requested changes

2023-06-27 17:19 UTC, tommygonzaleza commented on src/app/views/media/components/AssetMarkdown.js
> +  const diffSeconds = Math.abs((d1 - d2) / 1000);
Chequea que sea positiva la resta, si no es positiva no nos interesa mostrar el warning, solo nos interesa mostrar el warning cuando el readme se actualizo pero no se ha sincronizado con GitHub todavia, es decir no se ha hecho pull. Se debe validar que la diferencia sea positiva y de serlo, chequeas si es mayor a 20

2024-08-20 18:13 UTC, alesanchezr approved these changes

2024-08-20 18:13 UTC, merged