Add indexCustomField to obtain the utm_course from  custom_fields
breatheco-de/admin pull request #389
Opened 2024-11-27 00:01 UTC by avanegasp

<img width="1354" alt="image" src="https://github.com/user-attachments/assets/2acc6a14-8610-42a1-9ad7-acfcc82311e1">

2024-11-27 00:01 UTC, avanegasp commented
https://github.com/breatheco-de/breatheco-de/issues/7750

2024-12-10 14:12 UTC, tommygonzaleza requested changes

2024-12-12 16:34 UTC, tommygonzaleza approved these changes

2024-12-17 16:48 UTC, tommygonzaleza approved these changes

2024-12-17 16:51 UTC, merged