Input search bar and filter language
breatheco-de/admin pull request #391
Opened 2024-12-06 14:38 UTC by avanegasp

![search_and_lang](https://github.com/user-attachments/assets/d1840c7f-7d0f-4538-9620-80a98d4505b9)

2024-12-06 14:39 UTC, avanegasp commented
https://github.com/breatheco-de/breatheco-de/issues/7598

2024-12-10 14:15 UTC, tommygonzaleza commented on src/app/views/media/clusters.jsx
> +    const handleSearch = (value) => {
We have a hook to get the query from the url, here is the code: https://github.com/avanegasp/breatheco-admin/blob/c0b34b179c8938919fa62c9d58338ef76f749cc8/src/app/views/media/assets.jsx#L62

2024-12-10 14:20 UTC, tommygonzaleza commented on src/app/views/media/clusters.jsx
> +    useEffect(() => {
This useEffect is not necessary

2024-12-10 14:22 UTC, tommygonzaleza commented on src/app/views/media/clusters.jsx
> +                                    }}
You can move this to a function

2024-12-12 16:38 UTC, avanegasp commented on src/app/views/media/clusters.jsx
> +        ? clusters?.results.filter((cluster) =>
Done!

2024-12-12 16:39 UTC, avanegasp commented on src/app/views/media/clusters.jsx
> +    useEffect(() => {
Done!

2024-12-12 16:39 UTC, avanegasp commented on src/app/views/media/clusters.jsx
> +                                    }}
Done!

2025-01-07 11:54 UTC, tommygonzaleza requested changes

2025-01-07 11:54 UTC, tommygonzaleza commented on src/app/views/media/clusters.jsx
> +    const renderClusters = (clusters) => {
You can use ternary conditions because we only have one condition. This render function you created is a good practice but it should only be used when having nested ternary conditions.

2025-01-23 19:06 UTC, merged