Feature/convert/student/role
breatheco-de/admin pull request #88
Opened 2021-06-14 18:05 UTC by alexscoelho

Delivering : 

- [ ] Show modal window instead of automatically copy invite link #1505
- [ ] Convert Student Role on admissions/students, from icon and menu where it says "additional actions"
- [ ] Fixed Bulk Delete Code broken after refactoring on customtoolbar

2021-06-15 20:29 UTC, alesanchezr commented
- [ ] When updating a student role the view does not refresh after the successful update, I have to refresh the browser manually.
- [ ] On the student the  button "more actions" should say to change the student role.

2021-06-22 14:23 UTC, alesanchezr commented
Te falta todavia esto:  On the student the button "more actions" should say to change the student role.

2021-06-22 23:04 UTC, alesanchezr requested changes

2021-06-22 23:04 UTC, alesanchezr commented on src/app/views/admin/staff-form/StaffDetails.js
> +          setRole(data.role.replace("_", " "));
.find() instead of replacing the slug `_`

2021-06-22 23:04 UTC, alesanchezr commented on src/app/views/admissions/student-form/StudentDetails.js
> +          setRole(data.role.replace("_", " "));
.find en lugar de reemplzar el _

2021-06-22 23:12 UTC, alexscoelho commented on src/app/components/CopyInviteModal.js
> +            getMemberInvite(user);
![Screen Shot 2021-06-22 at 7 12 22 PM](https://user-images.githubusercontent.com/60261389/123011082-c726f280-d38d-11eb-895d-8f57e853bf70.png)

2021-06-23 00:27 UTC, alesanchezr approved these changes

2021-06-23 21:59 UTC, merged